'use strict';
// ══════════════════════════════════════════════════════════════
//  CAMALEÃO – Banco de Palabras – Español (ES)
// ══════════════════════════════════════════════════════════════

const CATEGORIES = [
    { id: 'esportes', label: '🏅 Deportes' },
    { id: 'animais', label: '🐾 Animales' },
    { id: 'comida', label: '🍕 Comida' },
    { id: 'musica', label: '🎵 Música' },
    { id: 'ciencia', label: '🔬 Ciencia' },
    { id: 'geografia', label: '🌍 Geografía' },
    { id: 'entretenimento', label: '🎬 Entretenimiento' },
    { id: 'cultura', label: '📚 Cultura' },
    { id: 'geral', label: '🎲 General' },
    { id: 'filmes', label: '🎥 Películas' },
    { id: 'series', label: '📺 Series' },
    { id: 'games', label: '🎮 Videojuegos' },
    { id: 'internet', label: '🌐 Internet' },
    { id: 'carros', label: '🚗 Autos' },
    { id: 'futebol', label: '⚽ Fútbol' },
    { id: 'cidades', label: '🏙️ Ciudades' },
    { id: 'culinaria', label: '🍽️ Gastronomía' },
    { id: 'tecnologia', label: '💻 Tecnología' },
    { id: 'natureza', label: '🌿 Naturaleza' },
    { id: 'moda', label: '👗 Moda' },
    { id: 'memes', label: '😂 Memes' },
];

const WORD_PAIRS = [

    // ── DEPORTES ──────────────────────────────────────────────
    { normal: 'Deporte', cam: 'Fútbol', cat: 'esportes' },
    { normal: 'Deporte', cam: 'Baloncesto', cat: 'esportes' },
    { normal: 'Deporte', cam: 'Voleibol', cat: 'esportes' },
    { normal: 'Deporte Olímpico', cam: 'Natación', cat: 'esportes' },
    { normal: 'Deporte Olímpico', cam: 'Atletismo', cat: 'esportes' },
    { normal: 'Deporte Olímpico', cam: 'Gimnasia', cat: 'esportes' },
    { normal: 'Deporte Extremo', cam: 'Skateboard', cat: 'esportes' },
    { normal: 'Deporte Extremo', cam: 'Surf', cat: 'esportes' },
    { normal: 'Deporte Extremo', cam: 'BMX', cat: 'esportes' },
    { normal: 'Arte Marcial', cam: 'Judo', cat: 'esportes' },
    { normal: 'Deporte de Raqueta', cam: 'Tenis', cat: 'esportes' },
    { normal: 'Deporte Colectivo', cam: 'Voleibol', cat: 'esportes' },
    { normal: 'Deporte Acuático', cam: 'Surf', cat: 'esportes' },
    { normal: 'Deporte de Invierno', cam: 'Esquí', cat: 'esportes' },
    { normal: 'Deporte de Combate', cam: 'Boxeo', cat: 'esportes' },
    { normal: 'Atletismo', cam: 'Salto de Longitud', cat: 'esportes' },
    { normal: 'Deporte con Pelota', cam: 'Baloncesto', cat: 'esportes' },

    // ── ANIMALES ──────────────────────────────────────────────
    { normal: 'Animal', cam: 'Perro', cat: 'animais' },
    { normal: 'Animal', cam: 'Elefante', cat: 'animais' },
    { normal: 'Animal', cam: 'León', cat: 'animais' },
    { normal: 'Mascota', cam: 'Gato', cat: 'animais' },
    { normal: 'Mascota', cam: 'Hámster', cat: 'animais' },
    { normal: 'Mascota', cam: 'Conejo', cat: 'animais' },
    { normal: 'Animal Marino', cam: 'Pulpo', cat: 'animais' },
    { normal: 'Animal Marino', cam: 'Tiburón', cat: 'animais' },
    { normal: 'Animal Marino', cam: 'Ballena', cat: 'animais' },
    { normal: 'Ave', cam: 'Tucán', cat: 'animais' },
    { normal: 'Ave', cam: 'Águila', cat: 'animais' },
    { normal: 'Ave', cam: 'Loro', cat: 'animais' },
    { normal: 'Insecto', cam: 'Abeja', cat: 'animais' },
    { normal: 'Insecto', cam: 'Hormiga', cat: 'animais' },
    { normal: 'Insecto', cam: 'Mariposa', cat: 'animais' },
    { normal: 'Mamífero Marino', cam: 'Delfín', cat: 'animais' },
    { normal: 'Reptil', cam: 'Serpiente', cat: 'animais' },
    { normal: 'Animal Africano', cam: 'León', cat: 'animais' },
    { normal: 'Animal Prehistórico', cam: 'Triceratops', cat: 'animais' },
    { normal: 'Animal Amazónico', cam: 'Jaguar', cat: 'animais' },
    { normal: 'Roedor', cam: 'Hámster', cat: 'animais' },
    { normal: 'Animal Venenoso', cam: 'Escorpión', cat: 'animais' },
    { normal: 'Ave de Rapiña', cam: 'Halcón', cat: 'animais' },

    // ── COMIDA ────────────────────────────────────────────────
    { normal: 'Comida', cam: 'Pizza', cat: 'comida' },
    { normal: 'Comida', cam: 'Hamburguesa', cat: 'comida' },
    { normal: 'Comida', cam: 'Lasaña', cat: 'comida' },
    { normal: 'Fruta', cam: 'Manzana', cat: 'comida' },
    { normal: 'Fruta', cam: 'Banana', cat: 'comida' },
    { normal: 'Fruta', cam: 'Mango', cat: 'comida' },
    { normal: 'Vegetal', cam: 'Zanahoria', cat: 'comida' },
    { normal: 'Vegetal', cam: 'Brócoli', cat: 'comida' },
    { normal: 'Vegetal', cam: 'Papa', cat: 'comida' },
    { normal: 'Bebida', cam: 'Café', cat: 'comida' },
    { normal: 'Bebida', cam: 'Jugo', cat: 'comida' },
    { normal: 'Bebida', cam: 'Refresco', cat: 'comida' },
    { normal: 'Dulce Brasileño', cam: 'Brigadeiro', cat: 'comida' },
    { normal: 'Dulce Brasileño', cam: 'Beijinho', cat: 'comida' },
    { normal: 'Dulce Brasileño', cam: 'Pé de Moleque', cat: 'comida' },
    { normal: 'Tipo de Queso', cam: 'Mozzarella', cat: 'comida' },
    { normal: 'Tipo de Queso', cam: 'Parmesano', cat: 'comida' },
    { normal: 'Tipo de Queso', cam: 'Cheddar', cat: 'comida' },
    { normal: 'Plato Brasileño', cam: 'Feijoada', cat: 'comida' },
    { normal: 'Fruta Tropical', cam: 'Mango', cat: 'comida' },
    { normal: 'Tipo de Pasta', cam: 'Lasaña', cat: 'comida' },
    { normal: 'Comida Rápida', cam: 'Hamburguesa', cat: 'comida' },
    { normal: 'Postre', cam: 'Helado', cat: 'comida' },
    { normal: 'Condimento', cam: 'Mostaza', cat: 'comida' },
    { normal: 'Bebida Alcohólica', cam: 'Cerveza', cat: 'comida' },
    { normal: 'Pan', cam: 'Croissant', cat: 'comida' },
    { normal: 'Legumbre', cam: 'Frijol', cat: 'comida' },

    // ── MÚSICA ────────────────────────────────────────────────
    { normal: 'Instrumento', cam: 'Guitarra', cat: 'musica' },
    { normal: 'Instrumento', cam: 'Piano', cat: 'musica' },
    { normal: 'Instrumento', cam: 'Batería', cat: 'musica' },
    { normal: 'Estilo Musical', cam: 'Funk', cat: 'musica' },
    { normal: 'Estilo Musical', cam: 'Rock', cat: 'musica' },
    { normal: 'Estilo Musical', cam: 'Country', cat: 'musica' },
    { normal: 'Banda Brasileña', cam: 'Legião Urbana', cat: 'musica' },
    { normal: 'Banda Brasileña', cam: 'Titãs', cat: 'musica' },
    { normal: 'Banda Brasileña', cam: 'Paralamas do Sucesso', cat: 'musica' },
    { normal: 'Instrumento de Percusión', cam: 'Batería', cat: 'musica' },
    { normal: 'Estilo Musical Americano', cam: 'Jazz', cat: 'musica' },
    { normal: 'Instrumento de Viento', cam: 'Saxofón', cat: 'musica' },
    { normal: 'Ritmo Nordestino', cam: 'Forró', cat: 'musica' },
    { normal: 'Estilo Electrónico', cam: 'Techno', cat: 'musica' },
    { normal: 'Instrumento de Cuerda', cam: 'Violín', cat: 'musica' },
    { normal: 'Género Afrobrasileño', cam: 'Samba', cat: 'musica' },
    { normal: 'Estilo Musical Británico', cam: 'Rock', cat: 'musica' },
    { normal: 'Instrumento de Teclado', cam: 'Piano', cat: 'musica' },

    // ── CIENCIA ───────────────────────────────────────────────
    { normal: 'Planeta', cam: 'Marte', cat: 'ciencia' },
    { normal: 'Planeta', cam: 'Júpiter', cat: 'ciencia' },
    { normal: 'Planeta', cam: 'Saturno', cat: 'ciencia' },
    { normal: 'Órgano del Cuerpo', cam: 'Corazón', cat: 'ciencia' },
    { normal: 'Órgano del Cuerpo', cam: 'Pulmón', cat: 'ciencia' },
    { normal: 'Órgano del Cuerpo', cam: 'Hígado', cat: 'ciencia' },
    { normal: 'Mineral', cam: 'Oro', cat: 'ciencia' },
    { normal: 'Mineral', cam: 'Plata', cat: 'ciencia' },
    { normal: 'Mineral', cam: 'Cuarzo', cat: 'ciencia' },
    { normal: 'Constelación', cam: 'Orión', cat: 'ciencia' },
    { normal: 'Constelación', cam: 'Escorpio', cat: 'ciencia' },
    { normal: 'Constelación', cam: 'Osa Mayor', cat: 'ciencia' },
    { normal: 'Elemento Químico', cam: 'Oxígeno', cat: 'ciencia' },
    { normal: 'Fenómeno Natural', cam: 'Terremoto', cat: 'ciencia' },
    { normal: 'Invento', cam: 'Radio', cat: 'ciencia' },
    { normal: 'Planeta Enano', cam: 'Plutón', cat: 'ciencia' },
    { normal: 'Teoría Científica', cam: 'Evolución', cat: 'ciencia' },
    { normal: 'Animal Extinto', cam: 'Dinosaurio', cat: 'ciencia' },
    { normal: 'Tipo de Energía', cam: 'Solar', cat: 'ciencia' },
    { normal: 'Parte del Cerebro', cam: 'Cerebelo', cat: 'ciencia' },
    { normal: 'Estrella', cam: 'Sol', cat: 'ciencia' },

    // ── GEOGRAFÍA ─────────────────────────────────────────────
    { normal: 'País', cam: 'Brasil', cat: 'geografia' },
    { normal: 'País', cam: 'Argentina', cat: 'geografia' },
    { normal: 'País', cam: 'Canadá', cat: 'geografia' },
    { normal: 'Capital Europea', cam: 'París', cat: 'geografia' },
    { normal: 'Capital Europea', cam: 'Roma', cat: 'geografia' },
    { normal: 'Capital Europea', cam: 'Madrid', cat: 'geografia' },
    { normal: 'Océano', cam: 'Pacífico', cat: 'geografia' },
    { normal: 'Océano', cam: 'Atlántico', cat: 'geografia' },
    { normal: 'Océano', cam: 'Índico', cat: 'geografia' },
    { normal: 'Continente', cam: 'África', cat: 'geografia' },
    { normal: 'Río Famoso', cam: 'Amazonas', cat: 'geografia' },
    { normal: 'Montaña', cam: 'Everest', cat: 'geografia' },
    { normal: 'Desierto', cam: 'Sahara', cat: 'geografia' },
    { normal: 'País Asiático', cam: 'Japón', cat: 'geografia' },
    { normal: 'Capital Sudamericana', cam: 'Buenos Aires', cat: 'geografia' },
    { normal: 'Isla Famosa', cam: 'Cuba', cat: 'geografia' },
    { normal: 'Estado Brasileño', cam: 'Bahia', cat: 'geografia' },
    { normal: 'Mar', cam: 'Mediterráneo', cat: 'geografia' },
    { normal: 'País Africano', cam: 'Egipto', cat: 'geografia' },

    // ── ENTRETENIMIENTO ────────────────────────────────────────
    { normal: 'Superhéroe', cam: 'Batman', cat: 'entretenimento' },
    { normal: 'Superhéroe', cam: 'Spider-Man', cat: 'entretenimento' },
    { normal: 'Superhéroe', cam: 'Superman', cat: 'entretenimento' },
    { normal: 'Personaje Disney', cam: 'Simba', cat: 'entretenimento' },
    { normal: 'Personaje Disney', cam: 'Mickey', cat: 'entretenimento' },
    { normal: 'Personaje Disney', cam: 'Elsa', cat: 'entretenimento' },
    { normal: 'Juego de Mesa', cam: 'Ajedrez', cat: 'entretenimento' },
    { normal: 'Juego de Mesa', cam: 'Monopoly', cat: 'entretenimento' },
    { normal: 'Juego de Mesa', cam: 'Risk', cat: 'entretenimento' },
    { normal: 'Personaje de Serie', cam: 'Walter White', cat: 'entretenimento' },
    { normal: 'Personaje de Serie', cam: 'Jon Snow', cat: 'entretenimento' },
    { normal: 'Personaje de Serie', cam: 'Eleven', cat: 'entretenimento' },
    { normal: 'Villano Disney', cam: 'Maléfica', cat: 'entretenimento' },
    { normal: 'Género de Película', cam: 'Terror', cat: 'entretenimento' },
    { normal: 'Personaje de Juego', cam: 'Mario', cat: 'entretenimento' },
    { normal: 'Animación Clásica', cam: 'Tom y Jerry', cat: 'entretenimento' },
    { normal: 'Serie de TV', cam: 'La Casa de Papel', cat: 'entretenimento' },
    { normal: 'Videojuego', cam: 'Minecraft', cat: 'entretenimento' },
    { normal: 'Personaje de Cómic', cam: 'Superman', cat: 'entretenimento' },
    { normal: 'Saga de Películas', cam: 'Star Wars', cat: 'entretenimento' },
    { normal: 'Género de Juego', cam: 'RPG', cat: 'entretenimento' },

    // ── CULTURA ───────────────────────────────────────────────
    { normal: 'Personaje Mítico', cam: 'Minotauro', cat: 'cultura' },
    { normal: 'Personaje Mítico', cam: 'Medusa', cat: 'cultura' },
    { normal: 'Personaje Mítico', cam: 'Zeus', cat: 'cultura' },
    { normal: 'Filósofo Griego', cam: 'Sócrates', cat: 'cultura' },
    { normal: 'Filósofo Griego', cam: 'Platón', cat: 'cultura' },
    { normal: 'Filósofo Griego', cam: 'Aristóteles', cat: 'cultura' },
    { normal: 'Signo del Zodiaco', cam: 'Aries', cat: 'cultura' },
    { normal: 'Signo del Zodiaco', cam: 'Leo', cat: 'cultura' },
    { normal: 'Signo del Zodiaco', cam: 'Escorpio', cat: 'cultura' },
    { normal: 'Género Literario', cam: 'Terror', cat: 'cultura' },
    { normal: 'Género Literario', cam: 'Fantasía', cat: 'cultura' },
    { normal: 'Género Literario', cam: 'Romance', cat: 'cultura' },
    { normal: 'Festividad Brasileña', cam: 'Carnaval', cat: 'cultura' },
    { normal: 'Personaje Histórico', cam: 'Cleopatra', cat: 'cultura' },
    { normal: 'Obra de Arte', cam: 'Mona Lisa', cat: 'cultura' },
    { normal: 'Religión', cam: 'Budismo', cat: 'cultura' },
    { normal: 'Deidad Nórdica', cam: 'Thor', cat: 'cultura' },
    { normal: 'Movimiento Artístico', cam: 'Barroco', cat: 'cultura' },
    { normal: 'Figura Mitológica', cam: 'Medusa', cat: 'cultura' },
    { normal: 'Libro Clásico', cam: 'Don Quijote', cat: 'cultura' },

    // ── GERAL ─────────────────────────────────────────────────
    { normal: 'Color', cam: 'Azul', cat: 'geral' },
    { normal: 'Color', cam: 'Rojo', cat: 'geral' },
    { normal: 'Color', cam: 'Verde', cat: 'geral' },
    { normal: 'Profesión', cam: 'Médico', cat: 'geral' },
    { normal: 'Profesión', cam: 'Profesor', cat: 'geral' },
    { normal: 'Profesión', cam: 'Ingeniero', cat: 'geral' },
    { normal: 'Transporte', cam: 'Autobús', cat: 'geral' },
    { normal: 'Transporte', cam: 'Avión', cat: 'geral' },
    { normal: 'Transporte', cam: 'Bicicleta', cat: 'geral' },
    { normal: 'Herramienta', cam: 'Martillo', cat: 'geral' },
    { normal: 'Herramienta', cam: 'Destornillador', cat: 'geral' },
    { normal: 'Herramienta', cam: 'Alicates', cat: 'geral' },
    { normal: 'Material Escolar', cam: 'Bolígrafo', cat: 'geral' },
    { normal: 'Material Escolar', cam: 'Lápiz', cat: 'geral' },
    { normal: 'Material Escolar', cam: 'Cuaderno', cat: 'geral' },
    { normal: 'Electrodoméstico', cam: 'Refrigerador', cat: 'geral' },
    { normal: 'Electrodoméstico', cam: 'Microondas', cat: 'geral' },
    { normal: 'Electrodoméstico', cam: 'Licuadora', cat: 'geral' },
    { normal: 'Ropa', cam: 'Camisa', cat: 'geral' },
    { normal: 'Ropa', cam: 'Pantalón', cat: 'geral' },
    { normal: 'Ropa', cam: 'Chaqueta', cat: 'geral' },
    { normal: 'Sentimiento', cam: 'Alegría', cat: 'geral' },
    { normal: 'Parte de la Casa', cam: 'Cocina', cat: 'geral' },
    { normal: 'Tipo de Vehículo', cam: 'Moto', cat: 'geral' },
    { normal: 'Mueble', cam: 'Sofá', cat: 'geral' },
    { normal: 'Profesión de Salud', cam: 'Dentista', cat: 'geral' },
    { normal: 'Objeto de Cocina', cam: 'Olla', cat: 'geral' },
    { normal: 'Estación del Año', cam: 'Verano', cat: 'geral' },
    { normal: 'Forma Geométrica', cam: 'Triángulo', cat: 'geral' },

    // ── FILMES ────────────────────────────────────────────────
    { normal: 'Película de Terror', cam: 'El Exorcista', cat: 'filmes' },
    { normal: 'Película de Ciencia Ficción', cam: 'Blade Runner', cat: 'filmes' },
    { normal: 'Película de Animación', cam: 'Toy Story', cat: 'filmes' },
    { normal: 'Director de Cine', cam: 'Christopher Nolan', cat: 'filmes' },

    // ── SERIES ────────────────────────────────────────────────
    { normal: 'Serie de Netflix', cam: 'Stranger Things', cat: 'series' },
    { normal: 'Serie de Drama', cam: 'Breaking Bad', cat: 'series' },
    { normal: 'Serie de Comedia', cam: 'The Office', cat: 'series' },
    { normal: 'Personaje de Serie', cam: 'Tony Soprano', cat: 'series' },

    // ── GAMES ─────────────────────────────────────────────────
    { normal: 'Consola de Videojuegos', cam: 'PlayStation 5', cat: 'games' },
    { normal: 'Juego de RPG', cam: 'The Witcher 3', cat: 'games' },
    { normal: 'Juego de FPS', cam: 'Counter-Strike', cat: 'games' },
    { normal: 'Personaje de Juego', cam: 'Mario', cat: 'games' },

    // ── INTERNET ──────────────────────────────────────────────
    { normal: 'Red Social', cam: 'Instagram', cat: 'internet' },
    { normal: 'App de Mensajería', cam: 'WhatsApp', cat: 'internet' },
    { normal: 'Plataforma de Video', cam: 'YouTube', cat: 'internet' },
    { normal: 'Sitio de Streaming', cam: 'Netflix', cat: 'internet' },

    // ── CARROS ────────────────────────────────────────────────
    { normal: 'Marca de Auto', cam: 'Toyota', cat: 'carros' },
    { normal: 'Auto Deportivo', cam: 'Ferrari', cat: 'carros' },
    { normal: 'Auto Popular', cam: 'Volkswagen', cat: 'carros' },
    { normal: 'SUV', cam: 'Compass', cat: 'carros' },

    // ── FUTEBOL ───────────────────────────────────────────────
    { normal: 'Equipo Brasileño', cam: 'Grêmio', cat: 'futebol' },
    { normal: 'Equipo Brasileño', cam: 'Flamengo', cat: 'futebol' },
    { normal: 'Jugador de Fútbol', cam: 'Pelé', cat: 'futebol' },
    { normal: 'Jugador de Fútbol', cam: 'Messi', cat: 'futebol' },

    // ── CIDADES ───────────────────────────────────────────────
    { normal: 'Ciudad Brasileña', cam: 'São Paulo', cat: 'cidades' },
    { normal: 'Ciudad Brasileña', cam: 'Río de Janeiro', cat: 'cidades' },
    { normal: 'Ciudad Turística', cam: 'París', cat: 'cidades' },
    { normal: 'Capital de América', cam: 'Washington', cat: 'cidades' },

    // ── CULINÁRIA ─────────────────────────────────────────────
    { normal: 'Plato Brasileño', cam: 'Feijoada', cat: 'culinaria' },
    { normal: 'Comida Callejera', cam: 'Pastel', cat: 'culinaria' },
    { normal: 'Comida Italiana', cam: 'Espagueti', cat: 'culinaria' },
    { normal: 'Postre', cam: 'Pudín', cat: 'culinaria' },

    // ── TECNOLOGIA ────────────────────────────────────────────
    { normal: 'Marca de Celular', cam: 'Samsung', cat: 'tecnologia' },
    { normal: 'Sistema Operativo', cam: 'Windows', cat: 'tecnologia' },
    { normal: 'Lenguaje de Programación', cam: 'JavaScript', cat: 'tecnologia' },
    { normal: 'Empresa de Tecnología', cam: 'Google', cat: 'tecnologia' },

    // ── NATUREZA ──────────────────────────────────────────────
    { normal: 'Árbol', cam: 'Roble', cat: 'natureza' },
    { normal: 'Flor', cam: 'Rosa', cat: 'natureza' },
    { normal: 'Bioma Brasileño', cam: 'Cerrado', cat: 'natureza' },

    // ── MODA ──────────────────────────────────────────────────
    { normal: 'Marca de Ropa', cam: 'Nike', cat: 'moda' },
    { normal: 'Accesorio', cam: 'Reloj', cat: 'moda' },
    { normal: 'Tipo de Calzado', cam: 'Tenis', cat: 'moda' },
    { normal: 'Prenda de Invierno', cam: 'Abrigo', cat: 'moda' },

    // ── MEMES ─────────────────────────────────────────────────
    { normal: 'Meme de Internet', cam: 'Doge', cat: 'memes' },
    { normal: 'Meme Brasileño', cam: 'Nazaré Confundida', cat: 'memes' },
    { normal: 'Expresión de Internet', cam: 'LOL', cat: 'memes' },
    { normal: 'Jerga de Internet', cam: 'Cringe', cat: 'memes' }
];

module.exports = { WORD_PAIRS, CATEGORIES };
