'use strict';
// ══════════════════════════════════════════════════════════════
//  CAMALEÃO – Banco de Palavras – Português (PT-BR)
// ══════════════════════════════════════════════════════════════

const CATEGORIES = [
    { id: 'esportes', label: '🏅 Esportes' },
    { id: 'animais', label: '🐾 Animais' },
    { id: 'comida', label: '🍕 Comida' },
    { id: 'musica', label: '🎵 Música' },
    { id: 'ciencia', label: '🔬 Ciência' },
    { id: 'geografia', label: '🌍 Geografia' },
    { id: 'entretenimento', label: '🎬 Entretenimento' },
    { id: 'cultura', label: '📚 Cultura' },
    { id: 'geral', label: '🎲 Geral' },
    { id: 'filmes', label: '🎥 Filmes' },
    { id: 'series', label: '📺 Séries' },
    { id: 'games', label: '🎮 Games' },
    { id: 'internet', label: '🌐 Internet' },
    { id: 'carros', label: '🚗 Carros' },
    { id: 'futebol', label: '⚽ Futebol' },
    { id: 'cidades', label: '🏙️ Cidades' },
    { id: 'culinaria', label: '🍽️ Culinária' },
    { id: 'tecnologia', label: '💻 Tecnologia' },
    { id: 'natureza', label: '🌿 Natureza' },
    { id: 'moda', label: '👗 Moda' },
    { id: 'memes', label: '😂 Memes' },
];

const WORD_PAIRS = [

    // ── ESPORTES ──────────────────────────────────────────────
    { normal: 'Esporte', cam: 'Futebol', cat: 'esportes' },
    { normal: 'Esporte', cam: 'Basquete', cat: 'esportes' },
    { normal: 'Esporte', cam: 'Vôlei', cat: 'esportes' },
    { normal: 'Esporte Olímpico', cam: 'Natação', cat: 'esportes' },
    { normal: 'Esporte Olímpico', cam: 'Atletismo', cat: 'esportes' },
    { normal: 'Esporte Olímpico', cam: 'Ginástica', cat: 'esportes' },
    { normal: 'Esporte Radical', cam: 'Skate', cat: 'esportes' },
    { normal: 'Esporte Radical', cam: 'Surf', cat: 'esportes' },
    { normal: 'Esporte Radical', cam: 'BMX', cat: 'esportes' },
    { normal: 'Arte Marcial', cam: 'Judô', cat: 'esportes' },
    { normal: 'Esporte de Raquete', cam: 'Tênis', cat: 'esportes' },
    { normal: 'Esporte Coletivo', cam: 'Vôlei', cat: 'esportes' },
    { normal: 'Esporte Aquático', cam: 'Surfe', cat: 'esportes' },
    { normal: 'Esporte de Inverno', cam: 'Esqui', cat: 'esportes' },
    { normal: 'Esporte de Combate', cam: 'Boxe', cat: 'esportes' },
    { normal: 'Atletismo', cam: 'Salto em Distância', cat: 'esportes' },
    { normal: 'Esporte com Bola', cam: 'Basquete', cat: 'esportes' },

    // ── ANIMAIS ───────────────────────────────────────────────
    { normal: 'Animal', cam: 'Cachorro', cat: 'animais' },
    { normal: 'Animal', cam: 'Elefante', cat: 'animais' },
    { normal: 'Animal', cam: 'Leão', cat: 'animais' },
    { normal: 'Animal Doméstico', cam: 'Gato', cat: 'animais' },
    { normal: 'Animal Doméstico', cam: 'Hamster', cat: 'animais' },
    { normal: 'Animal Doméstico', cam: 'Coelho', cat: 'animais' },
    { normal: 'Bicho do Mar', cam: 'Polvo', cat: 'animais' },
    { normal: 'Bicho do Mar', cam: 'Tubarão', cat: 'animais' },
    { normal: 'Bicho do Mar', cam: 'Baleia', cat: 'animais' },
    { normal: 'Ave', cam: 'Tucano', cat: 'animais' },
    { normal: 'Ave', cam: 'Águia', cat: 'animais' },
    { normal: 'Ave', cam: 'Papagaio', cat: 'animais' },
    { normal: 'Inseto', cam: 'Abelha', cat: 'animais' },
    { normal: 'Inseto', cam: 'Formiga', cat: 'animais' },
    { normal: 'Inseto', cam: 'Borboleta', cat: 'animais' },
    { normal: 'Mamífero Marinho', cam: 'Golfinho', cat: 'animais' },
    { normal: 'Réptil', cam: 'Cobra', cat: 'animais' },
    { normal: 'Animal Africano', cam: 'Leão', cat: 'animais' },
    { normal: 'Animal Pré-Histórico', cam: 'Triceratops', cat: 'animais' },
    { normal: 'Animal da Amazônia', cam: 'Onça', cat: 'animais' },
    { normal: 'Roedor', cam: 'Hamster', cat: 'animais' },
    { normal: 'Animal Venenoso', cam: 'Escorpião', cat: 'animais' },
    { normal: 'Ave de Rapina', cam: 'Falcão', cat: 'animais' },

    // ── COMIDA ────────────────────────────────────────────────
    { normal: 'Comida', cam: 'Pizza', cat: 'comida' },
    { normal: 'Comida', cam: 'Hambúrguer', cat: 'comida' },
    { normal: 'Comida', cam: 'Lasanha', cat: 'comida' },
    { normal: 'Fruta', cam: 'Maçã', cat: 'comida' },
    { normal: 'Fruta', cam: 'Banana', cat: 'comida' },
    { normal: 'Fruta', cam: 'Manga', cat: 'comida' },
    { normal: 'Vegetal', cam: 'Cenoura', cat: 'comida' },
    { normal: 'Vegetal', cam: 'Brócolis', cat: 'comida' },
    { normal: 'Vegetal', cam: 'Batata', cat: 'comida' },
    { normal: 'Bebida', cam: 'Café', cat: 'comida' },
    { normal: 'Bebida', cam: 'Suco', cat: 'comida' },
    { normal: 'Bebida', cam: 'Refrigerante', cat: 'comida' },
    { normal: 'Doce Brasileiro', cam: 'Brigadeiro', cat: 'comida' },
    { normal: 'Doce Brasileiro', cam: 'Beijinho', cat: 'comida' },
    { normal: 'Doce Brasileiro', cam: 'Pé de Moleque', cat: 'comida' },
    { normal: 'Tipo de Queijo', cam: 'Mussarela', cat: 'comida' },
    { normal: 'Tipo de Queijo', cam: 'Parmesão', cat: 'comida' },
    { normal: 'Tipo de Queijo', cam: 'Cheddar', cat: 'comida' },
    { normal: 'Prato Típico Brasileiro', cam: 'Feijoada', cat: 'comida' },
    { normal: 'Fruta Tropical', cam: 'Manga', cat: 'comida' },
    { normal: 'Tipo de Massa', cam: 'Lasanha', cat: 'comida' },
    { normal: 'Fast Food', cam: 'Hambúrguer', cat: 'comida' },
    { normal: 'Sobremesa', cam: 'Sorvete', cat: 'comida' },
    { normal: 'Condimento', cam: 'Mostarda', cat: 'comida' },
    { normal: 'Bebida Alcoólica', cam: 'Cerveja', cat: 'comida' },
    { normal: 'Pão', cam: 'Croissant', cat: 'comida' },
    { normal: 'Leguminosa', cam: 'Feijão', cat: 'comida' },

    // ── MÚSICA ────────────────────────────────────────────────
    { normal: 'Instrumento', cam: 'Violão', cat: 'musica' },
    { normal: 'Instrumento', cam: 'Piano', cat: 'musica' },
    { normal: 'Instrumento', cam: 'Bateria', cat: 'musica' },
    { normal: 'Estilo Musical', cam: 'Funk', cat: 'musica' },
    { normal: 'Estilo Musical', cam: 'Rock', cat: 'musica' },
    { normal: 'Estilo Musical', cam: 'Sertanejo', cat: 'musica' },
    { normal: 'Banda Brasileira', cam: 'Legião Urbana', cat: 'musica' },
    { normal: 'Banda Brasileira', cam: 'Titãs', cat: 'musica' },
    { normal: 'Banda Brasileira', cam: 'Paralamas do Sucesso', cat: 'musica' },
    { normal: 'Instrumento de Percussão', cam: 'Bateria', cat: 'musica' },
    { normal: 'Estilo Musical Americano', cam: 'Jazz', cat: 'musica' },
    { normal: 'Instrumento de Sopro', cam: 'Saxofone', cat: 'musica' },
    { normal: 'Ritmo Nordestino', cam: 'Forró', cat: 'musica' },
    { normal: 'Estilo Eletrônico', cam: 'Techno', cat: 'musica' },
    { normal: 'Instrumento de Corda', cam: 'Violino', cat: 'musica' },
    { normal: 'Gênero Afro-Brasileiro', cam: 'Samba', cat: 'musica' },
    { normal: 'Estilo Musical Britânico', cam: 'Rock', cat: 'musica' },
    { normal: 'Instrumento de Teclado', cam: 'Piano', cat: 'musica' },

    // ── CIÊNCIA ───────────────────────────────────────────────
    { normal: 'Planeta', cam: 'Marte', cat: 'ciencia' },
    { normal: 'Planeta', cam: 'Júpiter', cat: 'ciencia' },
    { normal: 'Planeta', cam: 'Saturno', cat: 'ciencia' },
    { normal: 'Órgão do Corpo', cam: 'Coração', cat: 'ciencia' },
    { normal: 'Órgão do Corpo', cam: 'Pulmão', cat: 'ciencia' },
    { normal: 'Órgão do Corpo', cam: 'Fígado', cat: 'ciencia' },
    { normal: 'Mineral', cam: 'Ouro', cat: 'ciencia' },
    { normal: 'Mineral', cam: 'Prata', cat: 'ciencia' },
    { normal: 'Mineral', cam: 'Quartzo', cat: 'ciencia' },
    { normal: 'Constelação', cam: 'Órion', cat: 'ciencia' },
    { normal: 'Constelação', cam: 'Escorpião', cat: 'ciencia' },
    { normal: 'Constelação', cam: 'Ursa Maior', cat: 'ciencia' },
    { normal: 'Elemento Químico', cam: 'Oxigênio', cat: 'ciencia' },
    { normal: 'Fenômeno Natural', cam: 'Terremoto', cat: 'ciencia' },
    { normal: 'Invenção', cam: 'Rádio', cat: 'ciencia' },
    { normal: 'Planeta Anão', cam: 'Plutão', cat: 'ciencia' },
    { normal: 'Teoria Científica', cam: 'Evolução', cat: 'ciencia' },
    { normal: 'Animal Extinto', cam: 'Dinossauro', cat: 'ciencia' },
    { normal: 'Tipo de Energia', cam: 'Solar', cat: 'ciencia' },
    { normal: 'Parte do Cérebro', cam: 'Cerebelo', cat: 'ciencia' },
    { normal: 'Estrela', cam: 'Sol', cat: 'ciencia' },

    // ── GEOGRAFIA ─────────────────────────────────────────────
    { normal: 'País', cam: 'Brasil', cat: 'geografia' },
    { normal: 'País', cam: 'Argentina', cat: 'geografia' },
    { normal: 'País', cam: 'Canadá', cat: 'geografia' },
    { normal: 'Capital Europeia', cam: 'Paris', cat: 'geografia' },
    { normal: 'Capital Europeia', cam: 'Roma', cat: 'geografia' },
    { normal: 'Capital Europeia', cam: 'Madri', cat: 'geografia' },
    { normal: 'Oceano', cam: 'Pacífico', cat: 'geografia' },
    { normal: 'Oceano', cam: 'Atlântico', cat: 'geografia' },
    { normal: 'Oceano', cam: 'Índico', cat: 'geografia' },
    { normal: 'Continente', cam: 'África', cat: 'geografia' },
    { normal: 'Rio Famoso', cam: 'Amazonas', cat: 'geografia' },
    { normal: 'Montanha', cam: 'Everest', cat: 'geografia' },
    { normal: 'Deserto', cam: 'Saara', cat: 'geografia' },
    { normal: 'País Asiático', cam: 'Japão', cat: 'geografia' },
    { normal: 'Capital Sul-Americana', cam: 'Buenos Aires', cat: 'geografia' },
    { normal: 'Ilha Famosa', cam: 'Cuba', cat: 'geografia' },
    { normal: 'Estado Brasileiro', cam: 'Bahia', cat: 'geografia' },
    { normal: 'Mar', cam: 'Mediterrâneo', cat: 'geografia' },
    { normal: 'País Africano', cam: 'Egito', cat: 'geografia' },

    // ── ENTRETENIMENTO ────────────────────────────────────────
    { normal: 'Super-Herói', cam: 'Batman', cat: 'entretenimento' },
    { normal: 'Super-Herói', cam: 'Homem-Aranha', cat: 'entretenimento' },
    { normal: 'Super-Herói', cam: 'Superman', cat: 'entretenimento' },
    { normal: 'Personagem Disney', cam: 'Simba', cat: 'entretenimento' },
    { normal: 'Personagem Disney', cam: 'Mickey', cat: 'entretenimento' },
    { normal: 'Personagem Disney', cam: 'Elsa', cat: 'entretenimento' },
    { normal: 'Jogo de Tabuleiro', cam: 'Xadrez', cat: 'entretenimento' },
    { normal: 'Jogo de Tabuleiro', cam: 'Banco Imobiliário', cat: 'entretenimento' },
    { normal: 'Jogo de Tabuleiro', cam: 'War', cat: 'entretenimento' },
    { normal: 'Personagem de Série', cam: 'Walter White', cat: 'entretenimento' },
    { normal: 'Personagem de Série', cam: 'Jon Snow', cat: 'entretenimento' },
    { normal: 'Personagem de Série', cam: 'Eleven', cat: 'entretenimento' },
    { normal: 'Vilão da Disney', cam: 'Malévola', cat: 'entretenimento' },
    { normal: 'Gênero de Filme', cam: 'Terror', cat: 'entretenimento' },
    { normal: 'Personagem de Jogo', cam: 'Mario', cat: 'entretenimento' },
    { normal: 'Animação Clássica', cam: 'Tom e Jerry', cat: 'entretenimento' },
    { normal: 'Série de TV', cam: 'La Casa de Papel', cat: 'entretenimento' },
    { normal: 'Videogame', cam: 'Minecraft', cat: 'entretenimento' },
    { normal: 'Personagem de HQ', cam: 'Superman', cat: 'entretenimento' },
    { normal: 'Saga de Filmes', cam: 'Star Wars', cat: 'entretenimento' },
    { normal: 'Gênero de Jogo', cam: 'RPG', cat: 'entretenimento' },

    // ── CULTURA ───────────────────────────────────────────────
    { normal: 'Personagem Mítico', cam: 'Minotauro', cat: 'cultura' },
    { normal: 'Personagem Mítico', cam: 'Medusa', cat: 'cultura' },
    { normal: 'Personagem Mítico', cam: 'Zeus', cat: 'cultura' },
    { normal: 'Filósofo Grego', cam: 'Sócrates', cat: 'cultura' },
    { normal: 'Filósofo Grego', cam: 'Platão', cat: 'cultura' },
    { normal: 'Filósofo Grego', cam: 'Aristóteles', cat: 'cultura' },
    { normal: 'Signo', cam: 'Áries', cat: 'cultura' },
    { normal: 'Signo', cam: 'Leão', cat: 'cultura' },
    { normal: 'Signo', cam: 'Escorpião', cat: 'cultura' },
    { normal: 'Gênero Literário', cam: 'Terror', cat: 'cultura' },
    { normal: 'Gênero Literário', cam: 'Fantasia', cat: 'cultura' },
    { normal: 'Gênero Literário', cam: 'Romance', cat: 'cultura' },
    { normal: 'Festividade Brasileira', cam: 'Carnaval', cat: 'cultura' },
    { normal: 'Personagem Histórico', cam: 'Cleópatra', cat: 'cultura' },
    { normal: 'Obra de Arte', cam: 'Mona Lisa', cat: 'cultura' },
    { normal: 'Religião', cam: 'Budismo', cat: 'cultura' },
    { normal: 'Divindade Nórdica', cam: 'Thor', cat: 'cultura' },
    { normal: 'Movimento Artístico', cam: 'Barroco', cat: 'cultura' },
    { normal: 'Figura Mitológica', cam: 'Medusa', cat: 'cultura' },
    { normal: 'Livro Clássico', cam: 'Dom Quixote', cat: 'cultura' },

    // ── GERAL ─────────────────────────────────────────────────
    { normal: 'Cor', cam: 'Azul', cat: 'geral' },
    { normal: 'Cor', cam: 'Vermelho', cat: 'geral' },
    { normal: 'Cor', cam: 'Verde', cat: 'geral' },
    { normal: 'Profissão', cam: 'Médico', cat: 'geral' },
    { normal: 'Profissão', cam: 'Professor', cat: 'geral' },
    { normal: 'Profissão', cam: 'Engenheiro', cat: 'geral' },
    { normal: 'Transporte', cam: 'Ônibus', cat: 'geral' },
    { normal: 'Transporte', cam: 'Avião', cat: 'geral' },
    { normal: 'Transporte', cam: 'Bicicleta', cat: 'geral' },
    { normal: 'Ferramenta', cam: 'Martelo', cat: 'geral' },
    { normal: 'Ferramenta', cam: 'Chave de Fenda', cat: 'geral' },
    { normal: 'Ferramenta', cam: 'Alicate', cat: 'geral' },
    { normal: 'Material Escolar', cam: 'Caneta', cat: 'geral' },
    { normal: 'Material Escolar', cam: 'Lápis', cat: 'geral' },
    { normal: 'Material Escolar', cam: 'Caderno', cat: 'geral' },
    { normal: 'Eletrodoméstico', cam: 'Geladeira', cat: 'geral' },
    { normal: 'Eletrodoméstico', cam: 'Micro-ondas', cat: 'geral' },
    { normal: 'Eletrodoméstico', cam: 'Liquidificador', cat: 'geral' },
    { normal: 'Roupa', cam: 'Camisa', cat: 'geral' },
    { normal: 'Roupa', cam: 'Calça', cat: 'geral' },
    { normal: 'Roupa', cam: 'Jaqueta', cat: 'geral' },
    { normal: 'Sentimento', cam: 'Alegria', cat: 'geral' },
    { normal: 'Parte da Casa', cam: 'Cozinha', cat: 'geral' },
    { normal: 'Tipo de Veículo', cam: 'Moto', cat: 'geral' },
    { normal: 'Móvel', cam: 'Sofá', cat: 'geral' },
    { normal: 'Profissão de Saúde', cam: 'Dentista', cat: 'geral' },
    { normal: 'Objeto de Cozinha', cam: 'Panela', cat: 'geral' },
    { normal: 'Estação do Ano', cam: 'Verão', cat: 'geral' },
    { normal: 'Forma Geométrica', cam: 'Triângulo', cat: 'geral' },

    // ── FILMES ────────────────────────────────────────────────
    { normal: 'Filme de Terror', cam: 'O Exorcista', cat: 'filmes' },
    { normal: 'Filme de Ficção Científica', cam: 'Blade Runner', cat: 'filmes' },
    { normal: 'Filme de Animação', cam: 'Toy Story', cat: 'filmes' },
    { normal: 'Diretor de Cinema', cam: 'Christopher Nolan', cat: 'filmes' },

    // ── SÉRIES ────────────────────────────────────────────────
    { normal: 'Série da Netflix', cam: 'Stranger Things', cat: 'series' },
    { normal: 'Série de Drama', cam: 'Breaking Bad', cat: 'series' },
    { normal: 'Série de Comédia', cam: 'The Office', cat: 'series' },
    { normal: 'Personagem de Série', cam: 'Tony Soprano', cat: 'series' },

    // ── GAMES ─────────────────────────────────────────────────
    { normal: 'Console de Videogame', cam: 'PlayStation 5', cat: 'games' },
    { normal: 'Jogo de RPG', cam: 'The Witcher 3', cat: 'games' },
    { normal: 'Jogo de FPS', cam: 'Counter-Strike', cat: 'games' },
    { normal: 'Personagem de Game', cam: 'Mario', cat: 'games' },

    // ── INTERNET ──────────────────────────────────────────────
    { normal: 'Rede Social', cam: 'Instagram', cat: 'internet' },
    { normal: 'Aplicativo de Mensagem', cam: 'WhatsApp', cat: 'internet' },
    { normal: 'Plataforma de Vídeo', cam: 'YouTube', cat: 'internet' },
    { normal: 'Site de Streaming', cam: 'Netflix', cat: 'internet' },

    // ── CARROS ────────────────────────────────────────────────
    { normal: 'Marca de Carro', cam: 'Toyota', cat: 'carros' },
    { normal: 'Carro Esportivo', cam: 'Ferrari', cat: 'carros' },
    { normal: 'Carro Popular', cam: 'Gol', cat: 'carros' },
    { normal: 'SUV', cam: 'Compass', cat: 'carros' },

    // ── FUTEBOL ───────────────────────────────────────────────
    { normal: 'Time Brasileiro', cam: 'Grêmio', cat: 'futebol' },
    { normal: 'Time Brasileiro', cam: 'Flamengo', cat: 'futebol' },
    { normal: 'Jogador de Futebol', cam: 'Pelé', cat: 'futebol' },
    { normal: 'Jogador de Futebol', cam: 'Messi', cat: 'futebol' },

    // ── CIDADES ───────────────────────────────────────────────
    { normal: 'Cidade Brasileira', cam: 'São Paulo', cat: 'cidades' },
    { normal: 'Cidade Brasileira', cam: 'Porto Alegre', cat: 'cidades' },
    { normal: 'Cidade Turística', cam: 'Rio de Janeiro', cat: 'cidades' },
    { normal: 'Capital da América', cam: 'Washington', cat: 'cidades' },

    // ── CULINÁRIA ─────────────────────────────────────────────
    { normal: 'Prato Brasileiro', cam: 'Feijoada', cat: 'culinaria' },
    { normal: 'Comida de Rua', cam: 'Pastel', cat: 'culinaria' },
    { normal: 'Comida Italiana', cam: 'Spaghetti', cat: 'culinaria' },
    { normal: 'Sobremesa', cam: 'Pudim', cat: 'culinaria' },

    // ── TECNOLOGIA ────────────────────────────────────────────
    { normal: 'Marca de Celular', cam: 'Samsung', cat: 'tecnologia' },
    { normal: 'Sistema Operacional', cam: 'Windows', cat: 'tecnologia' },
    { normal: 'Linguagem de Programação', cam: 'JavaScript', cat: 'tecnologia' },
    { normal: 'Empresa de Tecnologia', cam: 'Google', cat: 'tecnologia' },

    // ── NATUREZA ──────────────────────────────────────────────
    { normal: 'Árvore', cam: 'Carvalho', cat: 'natureza' },
    { normal: 'Flor', cam: 'Rosa', cat: 'natureza' },
    { normal: 'Bioma Brasileiro', cam: 'Cerrado', cat: 'natureza' },

    // ── MODA ──────────────────────────────────────────────────
    { normal: 'Marca de Roupa', cam: 'Nike', cat: 'moda' },
    { normal: 'Acessório', cam: 'Relógio', cat: 'moda' },
    { normal: 'Tipo de Calçado', cam: 'Tênis', cat: 'moda' },
    { normal: 'Peça de Roupa de Inverno', cam: 'Casaco', cat: 'moda' },

    // ── MEMES ─────────────────────────────────────────────────
    { normal: 'Meme da Internet', cam: 'Doge', cat: 'memes' },
    { normal: 'Meme Brasileiro', cam: 'Nazaré Confusa', cat: 'memes' },
    { normal: 'Expressão da Internet', cam: 'LOL', cat: 'memes' },
    { normal: 'Gíria da Internet', cam: 'Cringe', cat: 'memes' },
];

module.exports = { WORD_PAIRS, CATEGORIES };
