'use strict';
// ══════════════════════════════════════════════════════════════
//  CAMALEÃO – Word Bank – English (EN)
// ══════════════════════════════════════════════════════════════

const CATEGORIES = [
    { id: 'esportes', label: '🏅 Sports' },
    { id: 'animais', label: '🐾 Animals' },
    { id: 'comida', label: '🍕 Food' },
    { id: 'musica', label: '🎵 Music' },
    { id: 'ciencia', label: '🔬 Science' },
    { id: 'geografia', label: '🌍 Geography' },
    { id: 'entretenimento', label: '🎬 Entertainment' },
    { id: 'cultura', label: '📚 Culture' },
    { id: 'geral', label: '🎲 General' },
    { id: 'filmes', label: '🎥 Movies' },
    { id: 'series', label: '📺 TV Shows' },
    { id: 'games', label: '🎮 Games' },
    { id: 'internet', label: '🌐 Internet' },
    { id: 'carros', label: '🚗 Cars' },
    { id: 'futebol', label: '⚽ Football' },
    { id: 'cidades', label: '🏙️ Cities' },
    { id: 'culinaria', label: '🍽️ Cuisine' },
    { id: 'tecnologia', label: '💻 Technology' },
    { id: 'natureza', label: '🌿 Nature' },
    { id: 'moda', label: '👗 Fashion' },
    { id: 'memes', label: '😂 Memes' },
];

const WORD_PAIRS = [

    // ── ESPORTES ──────────────────────────────────────────────
    { normal: 'Sport', cam: 'Soccer', cat: 'esportes' },
    { normal: 'Sport', cam: 'Basketball', cat: 'esportes' },
    { normal: 'Sport', cam: 'Volleyball', cat: 'esportes' },
    { normal: 'Olympic Sport', cam: 'Swimming', cat: 'esportes' },
    { normal: 'Olympic Sport', cam: 'Athletics', cat: 'esportes' },
    { normal: 'Olympic Sport', cam: 'Gymnastics', cat: 'esportes' },
    { normal: 'Extreme Sport', cam: 'Skateboarding', cat: 'esportes' },
    { normal: 'Extreme Sport', cam: 'Surfing', cat: 'esportes' },
    { normal: 'Extreme Sport', cam: 'BMX', cat: 'esportes' },
    { normal: 'Martial Art', cam: 'Judo', cat: 'esportes' },
    { normal: 'Racquet Sport', cam: 'Tennis', cat: 'esportes' },
    { normal: 'Team Sport', cam: 'Volleyball', cat: 'esportes' },
    { normal: 'Water Sport', cam: 'Surfing', cat: 'esportes' },
    { normal: 'Winter Sport', cam: 'Skiing', cat: 'esportes' },
    { normal: 'Combat Sport', cam: 'Boxing', cat: 'esportes' },
    { normal: 'Athletics', cam: 'Long Jump', cat: 'esportes' },
    { normal: 'Ball Sport', cam: 'Basketball', cat: 'esportes' },

    // ── ANIMAIS ───────────────────────────────────────────────
    { normal: 'Animal', cam: 'Dog', cat: 'animais' },
    { normal: 'Animal', cam: 'Elephant', cat: 'animais' },
    { normal: 'Animal', cam: 'Lion', cat: 'animais' },
    { normal: 'Pet', cam: 'Cat', cat: 'animais' },
    { normal: 'Pet', cam: 'Hamster', cat: 'animais' },
    { normal: 'Pet', cam: 'Rabbit', cat: 'animais' },
    { normal: 'Sea Creature', cam: 'Octopus', cat: 'animais' },
    { normal: 'Sea Creature', cam: 'Shark', cat: 'animais' },
    { normal: 'Sea Creature', cam: 'Whale', cat: 'animais' },
    { normal: 'Bird', cam: 'Toucan', cat: 'animais' },
    { normal: 'Bird', cam: 'Eagle', cat: 'animais' },
    { normal: 'Bird', cam: 'Parrot', cat: 'animais' },
    { normal: 'Insect', cam: 'Bee', cat: 'animais' },
    { normal: 'Insect', cam: 'Ant', cat: 'animais' },
    { normal: 'Insect', cam: 'Butterfly', cat: 'animais' },
    { normal: 'Marine Mammal', cam: 'Dolphin', cat: 'animais' },
    { normal: 'Reptile', cam: 'Snake', cat: 'animais' },
    { normal: 'African Animal', cam: 'Lion', cat: 'animais' },
    { normal: 'Prehistoric Animal', cam: 'Triceratops', cat: 'animais' },
    { normal: 'Amazonian Animal', cam: 'Jaguar', cat: 'animais' },
    { normal: 'Rodent', cam: 'Hamster', cat: 'animais' },
    { normal: 'Poisonous Animal', cam: 'Scorpion', cat: 'animais' },
    { normal: 'Bird of Prey', cam: 'Falcon', cat: 'animais' },

    // ── COMIDA ────────────────────────────────────────────────
    { normal: 'Food', cam: 'Pizza', cat: 'comida' },
    { normal: 'Food', cam: 'Burger', cat: 'comida' },
    { normal: 'Food', cam: 'Lasagna', cat: 'comida' },
    { normal: 'Fruit', cam: 'Apple', cat: 'comida' },
    { normal: 'Fruit', cam: 'Banana', cat: 'comida' },
    { normal: 'Fruit', cam: 'Mango', cat: 'comida' },
    { normal: 'Vegetable', cam: 'Carrot', cat: 'comida' },
    { normal: 'Vegetable', cam: 'Broccoli', cat: 'comida' },
    { normal: 'Vegetable', cam: 'Potato', cat: 'comida' },
    { normal: 'Drink', cam: 'Coffee', cat: 'comida' },
    { normal: 'Drink', cam: 'Juice', cat: 'comida' },
    { normal: 'Drink', cam: 'Soda', cat: 'comida' },
    { normal: 'Brazilian Sweet', cam: 'Brigadeiro', cat: 'comida' },
    { normal: 'Brazilian Sweet', cam: 'Beijinho', cat: 'comida' },
    { normal: 'Brazilian Sweet', cam: 'Pé de Moleque', cat: 'comida' },
    { normal: 'Type of Cheese', cam: 'Mozzarella', cat: 'comida' },
    { normal: 'Type of Cheese', cam: 'Parmesan', cat: 'comida' },
    { normal: 'Type of Cheese', cam: 'Cheddar', cat: 'comida' },
    { normal: 'Typical Brazilian Dish', cam: 'Feijoada', cat: 'comida' },
    { normal: 'Tropical Fruit', cam: 'Mango', cat: 'comida' },
    { normal: 'Type of Pasta', cam: 'Lasagna', cat: 'comida' },
    { normal: 'Fast Food', cam: 'Burger', cat: 'comida' },
    { normal: 'Dessert', cam: 'Ice Cream', cat: 'comida' },
    { normal: 'Condiment', cam: 'Mustard', cat: 'comida' },
    { normal: 'Alcoholic Drink', cam: 'Beer', cat: 'comida' },
    { normal: 'Bread', cam: 'Croissant', cat: 'comida' },
    { normal: 'Legume', cam: 'Beans', cat: 'comida' },

    // ── MÚSICA ────────────────────────────────────────────────
    { normal: 'Instrument', cam: 'Guitar', cat: 'musica' },
    { normal: 'Instrument', cam: 'Piano', cat: 'musica' },
    { normal: 'Instrument', cam: 'Drums', cat: 'musica' },
    { normal: 'Music Style', cam: 'Funk', cat: 'musica' },
    { normal: 'Music Style', cam: 'Rock', cat: 'musica' },
    { normal: 'Music Style', cam: 'Country', cat: 'musica' },
    { normal: 'Brazilian Band', cam: 'Legião Urbana', cat: 'musica' },
    { normal: 'Brazilian Band', cam: 'Titãs', cat: 'musica' },
    { normal: 'Brazilian Band', cam: 'Paralamas do Sucesso', cat: 'musica' },
    { normal: 'Percussion Instrument', cam: 'Drums', cat: 'musica' },
    { normal: 'American Music Style', cam: 'Jazz', cat: 'musica' },
    { normal: 'Wind Instrument', cam: 'Saxophone', cat: 'musica' },
    { normal: 'Northeastern Rhythm', cam: 'Forró', cat: 'musica' },
    { normal: 'Electronic Style', cam: 'Techno', cat: 'musica' },
    { normal: 'String Instrument', cam: 'Violin', cat: 'musica' },
    { normal: 'Afro-Brazilian Genre', cam: 'Samba', cat: 'musica' },
    { normal: 'British Music Style', cam: 'Rock', cat: 'musica' },
    { normal: 'Keyboard Instrument', cam: 'Piano', cat: 'musica' },

    // ── CIÊNCIA ───────────────────────────────────────────────
    { normal: 'Planet', cam: 'Mars', cat: 'ciencia' },
    { normal: 'Planet', cam: 'Jupiter', cat: 'ciencia' },
    { normal: 'Planet', cam: 'Saturn', cat: 'ciencia' },
    { normal: 'Body Organ', cam: 'Heart', cat: 'ciencia' },
    { normal: 'Body Organ', cam: 'Lungs', cat: 'ciencia' },
    { normal: 'Body Organ', cam: 'Liver', cat: 'ciencia' },
    { normal: 'Mineral', cam: 'Gold', cat: 'ciencia' },
    { normal: 'Mineral', cam: 'Silver', cat: 'ciencia' },
    { normal: 'Mineral', cam: 'Quartz', cat: 'ciencia' },
    { normal: 'Constellation', cam: 'Orion', cat: 'ciencia' },
    { normal: 'Constellation', cam: 'Scorpio', cat: 'ciencia' },
    { normal: 'Constellation', cam: 'Ursa Major', cat: 'ciencia' },
    { normal: 'Chemical Element', cam: 'Oxygen', cat: 'ciencia' },
    { normal: 'Natural Phenomenon', cam: 'Earthquake', cat: 'ciencia' },
    { normal: 'Invention', cam: 'Radio', cat: 'ciencia' },
    { normal: 'Dwarf Planet', cam: 'Pluto', cat: 'ciencia' },
    { normal: 'Scientific Theory', cam: 'Evolution', cat: 'ciencia' },
    { normal: 'Extinct Animal', cam: 'Dinosaur', cat: 'ciencia' },
    { normal: 'Type of Energy', cam: 'Solar', cat: 'ciencia' },
    { normal: 'Part of the Brain', cam: 'Cerebellum', cat: 'ciencia' },
    { normal: 'Star', cam: 'Sun', cat: 'ciencia' },

    // ── GEOGRAFIA ─────────────────────────────────────────────
    { normal: 'Country', cam: 'Brazil', cat: 'geografia' },
    { normal: 'Country', cam: 'Argentina', cat: 'geografia' },
    { normal: 'Country', cam: 'Canada', cat: 'geografia' },
    { normal: 'European Capital', cam: 'Paris', cat: 'geografia' },
    { normal: 'European Capital', cam: 'Rome', cat: 'geografia' },
    { normal: 'European Capital', cam: 'Madrid', cat: 'geografia' },
    { normal: 'Ocean', cam: 'Pacific', cat: 'geografia' },
    { normal: 'Ocean', cam: 'Atlantic', cat: 'geografia' },
    { normal: 'Ocean', cam: 'Indian', cat: 'geografia' },
    { normal: 'Continent', cam: 'Africa', cat: 'geografia' },
    { normal: 'Famous River', cam: 'Amazon', cat: 'geografia' },
    { normal: 'Mountain', cam: 'Everest', cat: 'geografia' },
    { normal: 'Desert', cam: 'Sahara', cat: 'geografia' },
    { normal: 'Asian Country', cam: 'Japan', cat: 'geografia' },
    { normal: 'South American Capital', cam: 'Buenos Aires', cat: 'geografia' },
    { normal: 'Famous Island', cam: 'Cuba', cat: 'geografia' },
    { normal: 'Brazilian State', cam: 'Bahia', cat: 'geografia' },
    { normal: 'Sea', cam: 'Mediterranean', cat: 'geografia' },
    { normal: 'African Country', cam: 'Egypt', cat: 'geografia' },

    // ── ENTRETENIMENTO ────────────────────────────────────────
    { normal: 'Superhero', cam: 'Batman', cat: 'entretenimento' },
    { normal: 'Superhero', cam: 'Spider-Man', cat: 'entretenimento' },
    { normal: 'Superhero', cam: 'Superman', cat: 'entretenimento' },
    { normal: 'Disney Character', cam: 'Simba', cat: 'entretenimento' },
    { normal: 'Disney Character', cam: 'Mickey', cat: 'entretenimento' },
    { normal: 'Disney Character', cam: 'Elsa', cat: 'entretenimento' },
    { normal: 'Board Game', cam: 'Chess', cat: 'entretenimento' },
    { normal: 'Board Game', cam: 'Monopoly', cat: 'entretenimento' },
    { normal: 'Board Game', cam: 'Risk', cat: 'entretenimento' },
    { normal: 'TV Character', cam: 'Walter White', cat: 'entretenimento' },
    { normal: 'TV Character', cam: 'Jon Snow', cat: 'entretenimento' },
    { normal: 'TV Character', cam: 'Eleven', cat: 'entretenimento' },
    { normal: 'Disney Villain', cam: 'Maleficent', cat: 'entretenimento' },
    { normal: 'Movie Genre', cam: 'Horror', cat: 'entretenimento' },
    { normal: 'Game Character', cam: 'Mario', cat: 'entretenimento' },
    { normal: 'Classic Animation', cam: 'Tom and Jerry', cat: 'entretenimento' },
    { normal: 'TV Series', cam: 'Money Heist', cat: 'entretenimento' },
    { normal: 'Videogame', cam: 'Minecraft', cat: 'entretenimento' },
    { normal: 'Comic Book Character', cam: 'Superman', cat: 'entretenimento' },
    { normal: 'Movie Saga', cam: 'Star Wars', cat: 'entretenimento' },
    { normal: 'Game Genre', cam: 'RPG', cat: 'entretenimento' },

    // ── CULTURA ───────────────────────────────────────────────
    { normal: 'Mythical Character', cam: 'Minotaur', cat: 'cultura' },
    { normal: 'Mythical Character', cam: 'Medusa', cat: 'cultura' },
    { normal: 'Mythical Character', cam: 'Zeus', cat: 'cultura' },
    { normal: 'Greek Philosopher', cam: 'Socrates', cat: 'cultura' },
    { normal: 'Greek Philosopher', cam: 'Plato', cat: 'cultura' },
    { normal: 'Greek Philosopher', cam: 'Aristotle', cat: 'cultura' },
    { normal: 'Zodiac Sign', cam: 'Aries', cat: 'cultura' },
    { normal: 'Zodiac Sign', cam: 'Leo', cat: 'cultura' },
    { normal: 'Zodiac Sign', cam: 'Scorpio', cat: 'cultura' },
    { normal: 'Literary Genre', cam: 'Horror', cat: 'cultura' },
    { normal: 'Literary Genre', cam: 'Fantasy', cat: 'cultura' },
    { normal: 'Literary Genre', cam: 'Romance', cat: 'cultura' },
    { normal: 'Brazilian Festivity', cam: 'Carnival', cat: 'cultura' },
    { normal: 'Historical Figure', cam: 'Cleopatra', cat: 'cultura' },
    { normal: 'Work of Art', cam: 'Mona Lisa', cat: 'cultura' },
    { normal: 'Religion', cam: 'Buddhism', cat: 'cultura' },
    { normal: 'Norse Deity', cam: 'Thor', cat: 'cultura' },
    { normal: 'Artistic Movement', cam: 'Baroque', cat: 'cultura' },
    { normal: 'Mythological Figure', cam: 'Medusa', cat: 'cultura' },
    { normal: 'Classic Book', cam: 'Don Quixote', cat: 'cultura' },

    // ── GERAL ─────────────────────────────────────────────────
    { normal: 'Color', cam: 'Blue', cat: 'geral' },
    { normal: 'Color', cam: 'Red', cat: 'geral' },
    { normal: 'Color', cam: 'Green', cat: 'geral' },
    { normal: 'Profession', cam: 'Doctor', cat: 'geral' },
    { normal: 'Profession', cam: 'Teacher', cat: 'geral' },
    { normal: 'Profession', cam: 'Engineer', cat: 'geral' },
    { normal: 'Transport', cam: 'Bus', cat: 'geral' },
    { normal: 'Transport', cam: 'Airplane', cat: 'geral' },
    { normal: 'Transport', cam: 'Bicycle', cat: 'geral' },
    { normal: 'Tool', cam: 'Hammer', cat: 'geral' },
    { normal: 'Tool', cam: 'Screwdriver', cat: 'geral' },
    { normal: 'Tool', cam: 'Pliers', cat: 'geral' },
    { normal: 'School Supply', cam: 'Pen', cat: 'geral' },
    { normal: 'School Supply', cam: 'Pencil', cat: 'geral' },
    { normal: 'School Supply', cam: 'Notebook', cat: 'geral' },
    { normal: 'Home Appliance', cam: 'Refrigerator', cat: 'geral' },
    { normal: 'Home Appliance', cam: 'Microwave', cat: 'geral' },
    { normal: 'Home Appliance', cam: 'Blender', cat: 'geral' },
    { normal: 'Clothing', cam: 'Shirt', cat: 'geral' },
    { normal: 'Clothing', cam: 'Pants', cat: 'geral' },
    { normal: 'Clothing', cam: 'Jacket', cat: 'geral' },
    { normal: 'Feeling', cam: 'Joy', cat: 'geral' },
    { normal: 'Part of the House', cam: 'Kitchen', cat: 'geral' },
    { normal: 'Type of Vehicle', cam: 'Motorcycle', cat: 'geral' },
    { normal: 'Furniture', cam: 'Sofa', cat: 'geral' },
    { normal: 'Health Profession', cam: 'Dentist', cat: 'geral' },
    { normal: 'Kitchen Object', cam: 'Pan', cat: 'geral' },
    { normal: 'Season', cam: 'Summer', cat: 'geral' },
    { normal: 'Geometric Shape', cam: 'Triangle', cat: 'geral' },

    // ── FILMES ────────────────────────────────────────────────
    { normal: 'Horror Movie', cam: 'The Exorcist', cat: 'filmes' },
    { normal: 'Sci-Fi Movie', cam: 'Blade Runner', cat: 'filmes' },
    { normal: 'Animated Movie', cam: 'Toy Story', cat: 'filmes' },
    { normal: 'Movie Director', cam: 'Christopher Nolan', cat: 'filmes' },

    // ── SÉRIES ────────────────────────────────────────────────
    { normal: 'Netflix Series', cam: 'Stranger Things', cat: 'series' },
    { normal: 'Drama Series', cam: 'Breaking Bad', cat: 'series' },
    { normal: 'Comedy Series', cam: 'The Office', cat: 'series' },
    { normal: 'Series Character', cam: 'Tony Soprano', cat: 'series' },

    // ── GAMES ─────────────────────────────────────────────────
    { normal: 'Video Game Console', cam: 'PlayStation 5', cat: 'games' },
    { normal: 'RPG Game', cam: 'The Witcher 3', cat: 'games' },
    { normal: 'FPS Game', cam: 'Counter-Strike', cat: 'games' },
    { normal: 'Game Character', cam: 'Mario', cat: 'games' },

    // ── INTERNET ──────────────────────────────────────────────
    { normal: 'Social Network', cam: 'Instagram', cat: 'internet' },
    { normal: 'Messaging App', cam: 'WhatsApp', cat: 'internet' },
    { normal: 'Video Platform', cam: 'YouTube', cat: 'internet' },
    { normal: 'Streaming Site', cam: 'Netflix', cat: 'internet' },

    // ── CARROS ────────────────────────────────────────────────
    { normal: 'Car Brand', cam: 'Toyota', cat: 'carros' },
    { normal: 'Sports Car', cam: 'Ferrari', cat: 'carros' },
    { normal: 'Popular Car', cam: 'Volkswagen', cat: 'carros' },
    { normal: 'SUV', cam: 'Compass', cat: 'carros' },

    // ── FUTEBOL ───────────────────────────────────────────────
    { normal: 'Brazilian Team', cam: 'Grêmio', cat: 'futebol' },
    { normal: 'Brazilian Team', cam: 'Flamengo', cat: 'futebol' },
    { normal: 'Soccer Player', cam: 'Pelé', cat: 'futebol' },
    { normal: 'Soccer Player', cam: 'Messi', cat: 'futebol' },

    // ── CIDADES ───────────────────────────────────────────────
    { normal: 'Brazilian City', cam: 'São Paulo', cat: 'cidades' },
    { normal: 'Brazilian City', cam: 'Rio de Janeiro', cat: 'cidades' },
    { normal: 'Tourist City', cam: 'Paris', cat: 'cidades' },
    { normal: 'American Capital', cam: 'Washington', cat: 'cidades' },

    // ── CULINÁRIA ─────────────────────────────────────────────
    { normal: 'Brazilian Dish', cam: 'Feijoada', cat: 'culinaria' },
    { normal: 'Street Food', cam: 'Pastel', cat: 'culinaria' },
    { normal: 'Italian Food', cam: 'Spaghetti', cat: 'culinaria' },
    { normal: 'Dessert', cam: 'Pudding', cat: 'culinaria' },

    // ── TECNOLOGIA ────────────────────────────────────────────
    { normal: 'Phone Brand', cam: 'Samsung', cat: 'tecnologia' },
    { normal: 'Operating System', cam: 'Windows', cat: 'tecnologia' },
    { normal: 'Programming Language', cam: 'JavaScript', cat: 'tecnologia' },
    { normal: 'Tech Company', cam: 'Google', cat: 'tecnologia' },

    // ── NATUREZA ──────────────────────────────────────────────
    { normal: 'Tree', cam: 'Oak', cat: 'natureza' },
    { normal: 'Flower', cam: 'Rose', cat: 'natureza' },
    { normal: 'Brazilian Biome', cam: 'Amazon Rainforest', cat: 'natureza' },

    // ── MODA ──────────────────────────────────────────────────
    { normal: 'Clothing Brand', cam: 'Nike', cat: 'moda' },
    { normal: 'Accessory', cam: 'Watch', cat: 'moda' },
    { normal: 'Type of Footwear', cam: 'Sneakers', cat: 'moda' },
    { normal: 'Winter Clothing Item', cam: 'Coat', cat: 'moda' },

    // ── MEMES ─────────────────────────────────────────────────
    { normal: 'Internet Meme', cam: 'Doge', cat: 'memes' },
    { normal: 'Brazilian Meme', cam: 'Confused Nazaré', cat: 'memes' },
    { normal: 'Internet Expression', cam: 'LOL', cat: 'memes' },
    { normal: 'Internet Slang', cam: 'Cringe', cat: 'memes' }
];

module.exports = { WORD_PAIRS, CATEGORIES };
